from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935ff2a7d649'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fec_alta', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('codigo_zip', sa.String(), nullable=True),
    sa.Column('credit_card_num', sa.LargeBinary, nullable=True),
    sa.Column('credit_card_ccv', sa.LargeBinary, nullable=True),
    sa.Column('cuenta_numero', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('geo_latitud', sa.String(), nullable=True),
    sa.Column('geo_longitud', sa.String(), nullable=True),
    sa.Column('color_favorito', sa.String(), nullable=True),
    sa.Column('foto_dni', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('auto', sa.String(), nullable=True),
    sa.Column('auto_modelo', sa.String(), nullable=True),
    sa.Column('auto_tipo', sa.String(), nullable=True),
    sa.Column('auto_color', sa.String(), nullable=True),
    sa.Column('cantidad_compras_realizadas', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('fec_birthday', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
